"""Coins table

Revision ID: 04136803554b
Revises: c697d8159255
Create Date: 2021-03-08 17:27:36.725362

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04136803554b'
down_revision = 'c697d8159255'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('coin', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_coin_timestamp'), 'coin', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_coin_timestamp'), table_name='coin')
    op.drop_column('coin', 'timestamp')
    # ### end Alembic commands ###
