"""empty message

Revision ID: 2874ee630452
Revises: 9caf508d4485
Create Date: 2021-05-06 17:32:00.834211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2874ee630452'
down_revision = '9caf508d4485'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('point')
    op.drop_table('user')
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.drop_index('ix_coin_timestamp')

    op.drop_table('coin')
    op.drop_table('followers')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('coin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['coin.id'], name='fk_followers_coin_id_coin'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_followers_user_id_user')
    )
    op.create_table('coin',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('coin_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('coin_id', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('name', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('symbol', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('current_price', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('market_cap', sa.VARCHAR(length=180), autoincrement=False, nullable=True),
    sa.Column('market_cap_rank', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('price_change_24h', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('price_change_7d', postgresql.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(length=180), autoincrement=False, nullable=True),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_coin'),
    postgresql_ignore_search_path=False
    )
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.create_index('ix_coin_timestamp', ['timestamp'], unique=False)

    op.create_table('user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('username', sa.VARCHAR(length=64), autoincrement=False, nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('password_hash', sa.VARCHAR(length=128), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='pk_user'),
    sa.UniqueConstraint('email', name='uq_user_email'),
    sa.UniqueConstraint('username', name='uq_user_username')
    )
    op.create_table('point',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('x', sa.VARCHAR(length=32), autoincrement=False, nullable=True),
    sa.Column('y', sa.VARCHAR(length=120), autoincrement=False, nullable=True),
    sa.Column('coin_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['coin.id'], name='fk_point_coin_id_coin'),
    sa.PrimaryKeyConstraint('id', name='pk_point')
    )
    # ### end Alembic commands ###
