"""empty message

Revision ID: 2f9ec1c407b2
Revises: 27d6813e8622
Create Date: 2021-03-16 21:33:11.230589

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2f9ec1c407b2'
down_revision = '27d6813e8622'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('coin_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['coin_id'], ['coin.id'], name=op.f('fk_followers_coin_id_coin')),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name=op.f('fk_followers_user_id_user'))
    )
    op.drop_table('subs')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subs',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['coin.id'], name='fk_subs_id_coin')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###
