"""empty message

Revision ID: 37ebfc0ab6f1
Revises: 4ad3dfaa738e
Create Date: 2021-03-13 18:11:43.718043

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '37ebfc0ab6f1'
down_revision = '4ad3dfaa738e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.String(length=180), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.drop_column('image')

    # ### end Alembic commands ###
