"""empty message

Revision ID: 3bb1a4c5b7da
Revises: d6739296acda
Create Date: 2021-03-16 21:02:05.741181

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3bb1a4c5b7da'
down_revision = 'd6739296acda'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subs',
    sa.Column('id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['coin.id'], name=op.f('fk_subs_id_coin'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subs')
    # ### end Alembic commands ###
