"""te

Revision ID: 46318c770988
Revises: d5395275f616
Create Date: 2021-03-29 14:43:43.218371

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '46318c770988'
down_revision = 'd5395275f616'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coin_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_point_coin_id_coin'), 'coin', ['coin_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('point', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_point_coin_id_coin'), type_='foreignkey')
        batch_op.drop_column('coin_id')

    # ### end Alembic commands ###
