"""empty message

Revision ID: 4ad3dfaa738e
Revises: f1e5e897965b
Create Date: 2021-03-10 22:01:58.427959

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ad3dfaa738e'
down_revision = 'f1e5e897965b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.drop_constraint('uq_coin_market_cap_rank', type_='unique')
        batch_op.drop_constraint('uq_coin_symbol', type_='unique')

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('uq_user_email'), ['email'])
        batch_op.create_unique_constraint(batch_op.f('uq_user_username'), ['username'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('uq_user_username'), type_='unique')
        batch_op.drop_constraint(batch_op.f('uq_user_email'), type_='unique')

    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.create_unique_constraint('uq_coin_symbol', ['symbol'])
        batch_op.create_unique_constraint('uq_coin_market_cap_rank', ['market_cap_rank'])

    # ### end Alembic commands ###
