"""id

Revision ID: 9caf508d4485
Revises: 46318c770988
Create Date: 2021-03-29 15:25:40.235529

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9caf508d4485'
down_revision = '46318c770988'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coin_id', sa.String(length=64), nullable=True))
        batch_op.drop_column('coin_id_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('coin_id_name', sa.VARCHAR(length=64), nullable=True))
        batch_op.drop_column('coin_id')

    # ### end Alembic commands ###
