"""empty message

Revision ID: cbb4464195b6
Revises: 37610730a8a3
Create Date: 2021-03-10 11:30:15.746661

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cbb4464195b6'
down_revision = '37610730a8a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ['market_cap_rank'])
        batch_op.create_unique_constraint(None, ['symbol'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')

    # ### end Alembic commands ###
