"""empty message

Revision ID: d6739296acda
Revises: 37ebfc0ab6f1
Create Date: 2021-03-14 16:50:00.712106

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd6739296acda'
down_revision = '37ebfc0ab6f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price_change_7d', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('coin', schema=None) as batch_op:
        batch_op.drop_column('price_change_7d')

    # ### end Alembic commands ###
